baseURL: 'https://uvt-fmi.netlify.app/'
languageCode: en-us
title: UVT FMI
theme: theme
taxonomies:
  tag: tags
  category: categories
  content: contents
params:
    profileMode:
        enabled: true
        imageUrl: "FMI.png"
        imageTitle: "Facultatea de Matematică si Informatică"
        imageWidth: 200
        imageHeight: 200
        title: "Proiecte colective. Stagii de practică. Lucrări de licență."
        subtitle: "Pagină dedicată studenților de la Facultatea de Matematică - Informatică, specializările de Informatică, Universitatea de Vest din Timișoara"


menu:
  main:
    - identifier: contents
      name: Contents
      url: /contents/
      weight: 1
